export const GET_CARS_REQUEST_SENT = "GET_CARS_REQUEST_SENT"
export const GET_CARS_REQUEST_SUCCESSFULL = "GET_CARS_REQUEST_SUCCESSFULL"
export const GET_CARS_REQUEST_FAILED = "GET_CARS_REQUEST_FAILED"